/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedChamadaRouteImport } from './routes/_authenticated/chamada'
import { Route as AuthenticatedCursosRouteImport } from './routes/_authenticated/cursos'
import { Route as AuthenticatedFrequenciaRouteImport } from './routes/_authenticated/frequencia'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as MatriculaConviteRouteImport } from './routes/matricula.$convite'
import { Route as AuthenticatedSalasIndexRouteImport } from './routes/_authenticated/salas.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChamadaRoute = AuthenticatedChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursosRoute = AuthenticatedCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFrequenciaRoute = AuthenticatedFrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MatriculaConviteRoute = MatriculaConviteRouteImport.update({
  id: '/matricula/$convite',
  path: '/matricula/$convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalasIndexRoute = AuthenticatedSalasIndexRouteImport.update({
  id: '/salas/',
  path: '/salas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chamada': typeof AuthenticatedChamadaRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/frequencia': typeof AuthenticatedFrequenciaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/matricula/$convite': typeof MatriculaConviteRoute
  '/salas/': typeof AuthenticatedSalasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chamada': typeof AuthenticatedChamadaRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/frequencia': typeof AuthenticatedFrequenciaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/matricula/$convite': typeof MatriculaConviteRoute
  '/salas': typeof AuthenticatedSalasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/chamada': typeof AuthenticatedChamadaRoute
  '/_authenticated/cursos': typeof AuthenticatedCursosRoute
  '/_authenticated/frequencia': typeof AuthenticatedFrequenciaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/matricula/$convite': typeof MatriculaConviteRoute
  '/_authenticated/salas/': typeof AuthenticatedSalasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chamada'
    | '/cursos'
    | '/frequencia'
    | '/painel'
    | '/matricula/$convite'
    | '/salas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chamada'
    | '/cursos'
    | '/frequencia'
    | '/painel'
    | '/matricula/$convite'
    | '/salas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/chamada'
    | '/_authenticated/cursos'
    | '/_authenticated/frequencia'
    | '/_authenticated/painel'
    | '/matricula/$convite'
    | '/_authenticated/salas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MatriculaConviteRoute: typeof MatriculaConviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chamada': {
      id: '/_authenticated/chamada'
      path: '/chamada'
      fullPath: '/chamada'
      preLoaderRoute: typeof AuthenticatedChamadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos': {
      id: '/_authenticated/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof AuthenticatedCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frequencia': {
      id: '/_authenticated/frequencia'
      path: '/frequencia'
      fullPath: '/frequencia'
      preLoaderRoute: typeof AuthenticatedFrequenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/matricula/$convite': {
      id: '/matricula/$convite'
      path: '/matricula/$convite'
      fullPath: '/matricula/$convite'
      preLoaderRoute: typeof MatriculaConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/salas/': {
      id: '/_authenticated/salas/'
      path: '/salas'
      fullPath: '/salas/'
      preLoaderRoute: typeof AuthenticatedSalasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChamadaRoute: typeof AuthenticatedChamadaRoute
  AuthenticatedCursosRoute: typeof AuthenticatedCursosRoute
  AuthenticatedFrequenciaRoute: typeof AuthenticatedFrequenciaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedSalasIndexRoute: typeof AuthenticatedSalasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChamadaRoute: AuthenticatedChamadaRoute,
  AuthenticatedCursosRoute: AuthenticatedCursosRoute,
  AuthenticatedFrequenciaRoute: AuthenticatedFrequenciaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedSalasIndexRoute: AuthenticatedSalasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MatriculaConviteRoute: MatriculaConviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
