/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAcessosRouteImport } from './routes/_authenticated/acessos'
import { Route as AuthenticatedAlunosRouteImport } from './routes/_authenticated/alunos'
import { Route as AuthenticatedCarteirinhasRouteImport } from './routes/_authenticated/carteirinhas'
import { Route as AuthenticatedChamadaRouteImport } from './routes/_authenticated/chamada'
import { Route as AuthenticatedCursosRouteImport } from './routes/_authenticated/cursos'
import { Route as AuthenticatedFrequenciaRouteImport } from './routes/_authenticated/frequencia'
import { Route as AuthenticatedMeuPainelRouteImport } from './routes/_authenticated/meu-painel'
import { Route as AuthenticatedMeusMateriaisRouteImport } from './routes/_authenticated/meus-materiais'
import { Route as AuthenticatedMinhasTarefasRouteImport } from './routes/_authenticated/minhas-tarefas'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPessoasRouteImport } from './routes/_authenticated/pessoas'
import { Route as AuthenticatedTrocarSenhaRouteImport } from './routes/_authenticated/trocar-senha'
import { Route as MatriculaConviteRouteImport } from './routes/matricula.$convite'
import { Route as AuthenticatedMateriaisIndexRouteImport } from './routes/_authenticated/materiais.index'
import { Route as AuthenticatedMateriaisAulaIdRouteImport } from './routes/_authenticated/materiais.$aulaId'
import { Route as AuthenticatedSalasIndexRouteImport } from './routes/_authenticated/salas.index'
import { Route as AuthenticatedSalasIdRouteImport } from './routes/_authenticated/salas.$id'
import { Route as AuthenticatedTarefasIndexRouteImport } from './routes/_authenticated/tarefas.index'
import { Route as AuthenticatedTarefasAulaIdRouteImport } from './routes/_authenticated/tarefas.$aulaId'
import { Route as AuthenticatedSalasIdProfessoresAulasRouteImport } from './routes/_authenticated/salas.$id_.professores-aulas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcessosRoute = AuthenticatedAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunosRoute = AuthenticatedAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteirinhasRoute =
  AuthenticatedCarteirinhasRouteImport.update({
    id: '/carteirinhas',
    path: '/carteirinhas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChamadaRoute = AuthenticatedChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursosRoute = AuthenticatedCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFrequenciaRoute = AuthenticatedFrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuPainelRoute = AuthenticatedMeuPainelRouteImport.update({
  id: '/meu-painel',
  path: '/meu-painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusMateriaisRoute =
  AuthenticatedMeusMateriaisRouteImport.update({
    id: '/meus-materiais',
    path: '/meus-materiais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhasTarefasRoute =
  AuthenticatedMinhasTarefasRouteImport.update({
    id: '/minhas-tarefas',
    path: '/minhas-tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPessoasRoute = AuthenticatedPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocarSenhaRoute =
  AuthenticatedTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const MatriculaConviteRoute = MatriculaConviteRouteImport.update({
  id: '/matricula/$convite',
  path: '/matricula/$convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMateriaisIndexRoute =
  AuthenticatedMateriaisIndexRouteImport.update({
    id: '/materiais/',
    path: '/materiais/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMateriaisAulaIdRoute =
  AuthenticatedMateriaisAulaIdRouteImport.update({
    id: '/materiais/$aulaId',
    path: '/materiais/$aulaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalasIndexRoute = AuthenticatedSalasIndexRouteImport.update({
  id: '/salas/',
  path: '/salas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalasIdRoute = AuthenticatedSalasIdRouteImport.update({
  id: '/salas/$id',
  path: '/salas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasIndexRoute =
  AuthenticatedTarefasIndexRouteImport.update({
    id: '/tarefas/',
    path: '/tarefas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasAulaIdRoute =
  AuthenticatedTarefasAulaIdRouteImport.update({
    id: '/tarefas/$aulaId',
    path: '/tarefas/$aulaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalasIdProfessoresAulasRoute =
  AuthenticatedSalasIdProfessoresAulasRouteImport.update({
    id: '/salas/$id_/professores-aulas',
    path: '/salas/$id/professores-aulas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/alunos': typeof AuthenticatedAlunosRoute
  '/carteirinhas': typeof AuthenticatedCarteirinhasRoute
  '/chamada': typeof AuthenticatedChamadaRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/frequencia': typeof AuthenticatedFrequenciaRoute
  '/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/meus-materiais': typeof AuthenticatedMeusMateriaisRoute
  '/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/matricula/$convite': typeof MatriculaConviteRoute
  '/materiais/$aulaId': typeof AuthenticatedMateriaisAulaIdRoute
  '/salas/$id': typeof AuthenticatedSalasIdRoute
  '/tarefas/$aulaId': typeof AuthenticatedTarefasAulaIdRoute
  '/materiais/': typeof AuthenticatedMateriaisIndexRoute
  '/salas/': typeof AuthenticatedSalasIndexRoute
  '/tarefas/': typeof AuthenticatedTarefasIndexRoute
  '/salas/$id/professores-aulas': typeof AuthenticatedSalasIdProfessoresAulasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/alunos': typeof AuthenticatedAlunosRoute
  '/carteirinhas': typeof AuthenticatedCarteirinhasRoute
  '/chamada': typeof AuthenticatedChamadaRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/frequencia': typeof AuthenticatedFrequenciaRoute
  '/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/meus-materiais': typeof AuthenticatedMeusMateriaisRoute
  '/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/matricula/$convite': typeof MatriculaConviteRoute
  '/materiais/$aulaId': typeof AuthenticatedMateriaisAulaIdRoute
  '/salas/$id': typeof AuthenticatedSalasIdRoute
  '/tarefas/$aulaId': typeof AuthenticatedTarefasAulaIdRoute
  '/materiais': typeof AuthenticatedMateriaisIndexRoute
  '/salas': typeof AuthenticatedSalasIndexRoute
  '/tarefas': typeof AuthenticatedTarefasIndexRoute
  '/salas/$id/professores-aulas': typeof AuthenticatedSalasIdProfessoresAulasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/acessos': typeof AuthenticatedAcessosRoute
  '/_authenticated/alunos': typeof AuthenticatedAlunosRoute
  '/_authenticated/carteirinhas': typeof AuthenticatedCarteirinhasRoute
  '/_authenticated/chamada': typeof AuthenticatedChamadaRoute
  '/_authenticated/cursos': typeof AuthenticatedCursosRoute
  '/_authenticated/frequencia': typeof AuthenticatedFrequenciaRoute
  '/_authenticated/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/_authenticated/meus-materiais': typeof AuthenticatedMeusMateriaisRoute
  '/_authenticated/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pessoas': typeof AuthenticatedPessoasRoute
  '/_authenticated/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/matricula/$convite': typeof MatriculaConviteRoute
  '/_authenticated/materiais/$aulaId': typeof AuthenticatedMateriaisAulaIdRoute
  '/_authenticated/salas/$id': typeof AuthenticatedSalasIdRoute
  '/_authenticated/tarefas/$aulaId': typeof AuthenticatedTarefasAulaIdRoute
  '/_authenticated/materiais/': typeof AuthenticatedMateriaisIndexRoute
  '/_authenticated/salas/': typeof AuthenticatedSalasIndexRoute
  '/_authenticated/tarefas/': typeof AuthenticatedTarefasIndexRoute
  '/_authenticated/salas/$id_/professores-aulas': typeof AuthenticatedSalasIdProfessoresAulasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esqueci-senha'
    | '/sitemap.xml'
    | '/acessos'
    | '/alunos'
    | '/carteirinhas'
    | '/chamada'
    | '/cursos'
    | '/frequencia'
    | '/meu-painel'
    | '/meus-materiais'
    | '/minhas-tarefas'
    | '/painel'
    | '/pessoas'
    | '/trocar-senha'
    | '/matricula/$convite'
    | '/materiais/$aulaId'
    | '/salas/$id'
    | '/tarefas/$aulaId'
    | '/materiais/'
    | '/salas/'
    | '/tarefas/'
    | '/salas/$id/professores-aulas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/sitemap.xml'
    | '/acessos'
    | '/alunos'
    | '/carteirinhas'
    | '/chamada'
    | '/cursos'
    | '/frequencia'
    | '/meu-painel'
    | '/meus-materiais'
    | '/minhas-tarefas'
    | '/painel'
    | '/pessoas'
    | '/trocar-senha'
    | '/matricula/$convite'
    | '/materiais/$aulaId'
    | '/salas/$id'
    | '/tarefas/$aulaId'
    | '/materiais'
    | '/salas'
    | '/tarefas'
    | '/salas/$id/professores-aulas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/esqueci-senha'
    | '/sitemap.xml'
    | '/_authenticated/acessos'
    | '/_authenticated/alunos'
    | '/_authenticated/carteirinhas'
    | '/_authenticated/chamada'
    | '/_authenticated/cursos'
    | '/_authenticated/frequencia'
    | '/_authenticated/meu-painel'
    | '/_authenticated/meus-materiais'
    | '/_authenticated/minhas-tarefas'
    | '/_authenticated/painel'
    | '/_authenticated/pessoas'
    | '/_authenticated/trocar-senha'
    | '/matricula/$convite'
    | '/_authenticated/materiais/$aulaId'
    | '/_authenticated/salas/$id'
    | '/_authenticated/tarefas/$aulaId'
    | '/_authenticated/materiais/'
    | '/_authenticated/salas/'
    | '/_authenticated/tarefas/'
    | '/_authenticated/salas/$id_/professores-aulas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MatriculaConviteRoute: typeof MatriculaConviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acessos': {
      id: '/_authenticated/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AuthenticatedAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos': {
      id: '/_authenticated/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AuthenticatedAlunosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteirinhas': {
      id: '/_authenticated/carteirinhas'
      path: '/carteirinhas'
      fullPath: '/carteirinhas'
      preLoaderRoute: typeof AuthenticatedCarteirinhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamada': {
      id: '/_authenticated/chamada'
      path: '/chamada'
      fullPath: '/chamada'
      preLoaderRoute: typeof AuthenticatedChamadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos': {
      id: '/_authenticated/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof AuthenticatedCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frequencia': {
      id: '/_authenticated/frequencia'
      path: '/frequencia'
      fullPath: '/frequencia'
      preLoaderRoute: typeof AuthenticatedFrequenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-painel': {
      id: '/_authenticated/meu-painel'
      path: '/meu-painel'
      fullPath: '/meu-painel'
      preLoaderRoute: typeof AuthenticatedMeuPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-materiais': {
      id: '/_authenticated/meus-materiais'
      path: '/meus-materiais'
      fullPath: '/meus-materiais'
      preLoaderRoute: typeof AuthenticatedMeusMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-tarefas': {
      id: '/_authenticated/minhas-tarefas'
      path: '/minhas-tarefas'
      fullPath: '/minhas-tarefas'
      preLoaderRoute: typeof AuthenticatedMinhasTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoas': {
      id: '/_authenticated/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AuthenticatedPessoasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocar-senha': {
      id: '/_authenticated/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof AuthenticatedTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/matricula/$convite': {
      id: '/matricula/$convite'
      path: '/matricula/$convite'
      fullPath: '/matricula/$convite'
      preLoaderRoute: typeof MatriculaConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/materiais/': {
      id: '/_authenticated/materiais/'
      path: '/materiais'
      fullPath: '/materiais/'
      preLoaderRoute: typeof AuthenticatedMateriaisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais/$aulaId': {
      id: '/_authenticated/materiais/$aulaId'
      path: '/materiais/$aulaId'
      fullPath: '/materiais/$aulaId'
      preLoaderRoute: typeof AuthenticatedMateriaisAulaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salas/': {
      id: '/_authenticated/salas/'
      path: '/salas'
      fullPath: '/salas/'
      preLoaderRoute: typeof AuthenticatedSalasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salas/$id': {
      id: '/_authenticated/salas/$id'
      path: '/salas/$id'
      fullPath: '/salas/$id'
      preLoaderRoute: typeof AuthenticatedSalasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/': {
      id: '/_authenticated/tarefas/'
      path: '/tarefas'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof AuthenticatedTarefasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/$aulaId': {
      id: '/_authenticated/tarefas/$aulaId'
      path: '/tarefas/$aulaId'
      fullPath: '/tarefas/$aulaId'
      preLoaderRoute: typeof AuthenticatedTarefasAulaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salas/$id_/professores-aulas': {
      id: '/_authenticated/salas/$id_/professores-aulas'
      path: '/salas/$id/professores-aulas'
      fullPath: '/salas/$id/professores-aulas'
      preLoaderRoute: typeof AuthenticatedSalasIdProfessoresAulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcessosRoute: typeof AuthenticatedAcessosRoute
  AuthenticatedAlunosRoute: typeof AuthenticatedAlunosRoute
  AuthenticatedCarteirinhasRoute: typeof AuthenticatedCarteirinhasRoute
  AuthenticatedChamadaRoute: typeof AuthenticatedChamadaRoute
  AuthenticatedCursosRoute: typeof AuthenticatedCursosRoute
  AuthenticatedFrequenciaRoute: typeof AuthenticatedFrequenciaRoute
  AuthenticatedMeuPainelRoute: typeof AuthenticatedMeuPainelRoute
  AuthenticatedMeusMateriaisRoute: typeof AuthenticatedMeusMateriaisRoute
  AuthenticatedMinhasTarefasRoute: typeof AuthenticatedMinhasTarefasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPessoasRoute: typeof AuthenticatedPessoasRoute
  AuthenticatedTrocarSenhaRoute: typeof AuthenticatedTrocarSenhaRoute
  AuthenticatedMateriaisAulaIdRoute: typeof AuthenticatedMateriaisAulaIdRoute
  AuthenticatedSalasIdRoute: typeof AuthenticatedSalasIdRoute
  AuthenticatedTarefasAulaIdRoute: typeof AuthenticatedTarefasAulaIdRoute
  AuthenticatedMateriaisIndexRoute: typeof AuthenticatedMateriaisIndexRoute
  AuthenticatedSalasIndexRoute: typeof AuthenticatedSalasIndexRoute
  AuthenticatedTarefasIndexRoute: typeof AuthenticatedTarefasIndexRoute
  AuthenticatedSalasIdProfessoresAulasRoute: typeof AuthenticatedSalasIdProfessoresAulasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcessosRoute: AuthenticatedAcessosRoute,
  AuthenticatedAlunosRoute: AuthenticatedAlunosRoute,
  AuthenticatedCarteirinhasRoute: AuthenticatedCarteirinhasRoute,
  AuthenticatedChamadaRoute: AuthenticatedChamadaRoute,
  AuthenticatedCursosRoute: AuthenticatedCursosRoute,
  AuthenticatedFrequenciaRoute: AuthenticatedFrequenciaRoute,
  AuthenticatedMeuPainelRoute: AuthenticatedMeuPainelRoute,
  AuthenticatedMeusMateriaisRoute: AuthenticatedMeusMateriaisRoute,
  AuthenticatedMinhasTarefasRoute: AuthenticatedMinhasTarefasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPessoasRoute: AuthenticatedPessoasRoute,
  AuthenticatedTrocarSenhaRoute: AuthenticatedTrocarSenhaRoute,
  AuthenticatedMateriaisAulaIdRoute: AuthenticatedMateriaisAulaIdRoute,
  AuthenticatedSalasIdRoute: AuthenticatedSalasIdRoute,
  AuthenticatedTarefasAulaIdRoute: AuthenticatedTarefasAulaIdRoute,
  AuthenticatedMateriaisIndexRoute: AuthenticatedMateriaisIndexRoute,
  AuthenticatedSalasIndexRoute: AuthenticatedSalasIndexRoute,
  AuthenticatedTarefasIndexRoute: AuthenticatedTarefasIndexRoute,
  AuthenticatedSalasIdProfessoresAulasRoute:
    AuthenticatedSalasIdProfessoresAulasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MatriculaConviteRoute: MatriculaConviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
